language: python
python:
  - "2.7"
  - "2.6"
virtualenv:
  - system_site_packages: true
before_install:
  - "cd python"
  - "sudo apt-get install -qq python-scipy python-numpy"
install: "pip install -r requirements.txt"
script: "trial smap"
